services:
  resm:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - USER=${USER}
        - HOME=${HOME}
    restart: always
    tty: true
    volumes:
      - ${REPO_DIR}:${HOME}/repo
      - ${ENV_DIR}:${HOME}/env
      - ${BACKUP_DIR}:${HOME}/bkup
    environment:
      - HOME=${HOME}
    command: >
      /bin/bash -c "
        resm init
        mkdir ${HOME}/.ssh
        mv config ${HOME}/.ssh/
        sudo chown ${USER} repo -R
        git config --global core.autocrlf true
        find ${HOME}/env -name \'*.pem\' -or -name \'*.ppk\' -exec chmod 600 {}; \\
        /bin/bash
      "
